# Use the flexible Node.js environment
runtime: nodejs
env: flex
service: backend

# Tell App Engine to use Node.js 20
runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

# Basic scaling (keeps 1 instance running)
automatic_scaling:
  min_num_instances: 1

# Health checks for your /health endpoint
readiness_check:
  path: '/health'
liveness_check:
  path: '/health'

# NO ENVIRONMENT VARIABLES NEEDED